server:
  port: 8030

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false


app:
  datasource:
    test:
      url: jdbc:mysql://192.168.200.51:3306/test2
      username: root
      password: PCIaVcdT